### ISSUE TITLE
Single compilation step

### ISSUE THREAD

**Issue by james-d-mitchell** [sebasguts/NautyTracesInterface#3]
It'd be great if it was possible to just build nauty/traces and `NautyTracesInterface` at the same time, i.e. not be required to build nauty first and then `NautyTracesInterface`. 

Also in `configure.ac` it'd be good to check if `nauty` is available.

**Comment by sebasguts** [comment]
You need to use the nauty version that comes with the package anyway, as we patched the nauty configuration for compilation. So should it check if nauty is compiled?
