### ISSUE TITLE
Doesn't work in 32-bit mode

### ISSUE THREAD

**Issue by james-d-mitchell** [sebasguts/NautyTracesInterface#5]
It seems that `NautyTracesInterface` does not function correctly in 32-bit mode. It loads fine, but when trying to find the automorphism group an error is returned. See:

https://travis-ci.org/gap-packages/Digraphs/jobs/303648682

for more details.

**Comment by sebasguts** [comment]
This is fixed by passing the appropriate flags to nauty.
